apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- github.com/yeongseoksong/cloud-native-spring/catalog-service/k8s?ref=main
patches:
- path: patch-env.yml
configMapGenerator:
- behavior: merge
  files:
  - application-staging.yml
  name: catalog-config
images:
- name: catalog-service
  newName: ghcr.io/yeongseoksong/catalog-service
  newTag: latest
replicas:
  - count: 2
    name: catalog-service