apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-config
  labels:
    app: catalog-service
data:
  application.yml: |
    polar: # config server 설정 값이 우선되어 무시
      greeting: Welcome to the local book catalog from Kubernetes!
    spring:
      datasource:
        url: jdbc:postgresql://polar-postgres/polardb_catalog
    security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: http://localhost:8080/realms/PolarBookshop
        
